name: notify-release
on:
  workflow_dispatch:
#  schedule:
#    - cron: '30 8 * * *'
  release:
    types: [published]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Notify release
        uses: nearform/github-action-notify-release@fix/notify-after-default
        with:
          stale-days: '1'
